Write a function so that the columns of the output matrix are powers of the input
vector.


In [3]:
import numpy as np

In [6]:
x = np.array([1,2,3])
N = 3
ans = np.vander(x, N)
print(ans)


[[1 1 1]
 [4 2 1]
 [9 3 1]]


Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [8]:
x = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [16]:
def mov_avg_val(mylist, N):
    cumsum, moving_aves = [0], []
    for i, x in enumerate(mylist, 1):
        cumsum.append(cumsum[i-1] + x) 
        if i>=N:
            moving_ave = round(((cumsum[i] - cumsum[i-N])/N),2) #computing the moving average using array sum array cumsum
        
            moving_aves.append(moving_ave) # listing the moving average as an single array
    print("Moving average : ", moving_aves)


In [17]:

mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = 3

mov_avg_val(mylist,N)

Moving average :  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
